/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumItemCategory } from "./EnumItemCategory";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { InventoryItemListRelationFilter } from "../../inventoryItem/base/InventoryItemListRelationFilter";
import { PlantWhereUniqueInput } from "../../plant/base/PlantWhereUniqueInput";
@InputType()
class ItemWhereInput {
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  cashPrice?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumItemCategory,
  })
  @IsEnum(EnumItemCategory)
  @IsOptional()
  @Field(() => EnumItemCategory, {
    nullable: true,
  })
  category?: "seed";

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  creditsPrice?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  displayName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => InventoryItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InventoryItemListRelationFilter)
  @IsOptional()
  @Field(() => InventoryItemListRelationFilter, {
    nullable: true,
  })
  inventoryItem?: InventoryItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PlantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlantWhereUniqueInput)
  @IsOptional()
  @Field(() => PlantWhereUniqueInput, {
    nullable: true,
  })
  plant?: PlantWhereUniqueInput;
}
export { ItemWhereInput };
