/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CropUpdateManyWithoutFarmsInput } from "./CropUpdateManyWithoutFarmsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { InventoryItemUpdateManyWithoutFarmsInput } from "./InventoryItemUpdateManyWithoutFarmsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class FarmUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CropUpdateManyWithoutFarmsInput,
  })
  @ValidateNested()
  @Type(() => CropUpdateManyWithoutFarmsInput)
  @IsOptional()
  @Field(() => CropUpdateManyWithoutFarmsInput, {
    nullable: true,
  })
  crops?: CropUpdateManyWithoutFarmsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  displayName?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryItemUpdateManyWithoutFarmsInput,
  })
  @ValidateNested()
  @Type(() => InventoryItemUpdateManyWithoutFarmsInput)
  @IsOptional()
  @Field(() => InventoryItemUpdateManyWithoutFarmsInput, {
    nullable: true,
  })
  inventoryItems?: InventoryItemUpdateManyWithoutFarmsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  owner?: UserWhereUniqueInput | null;
}
export { FarmUpdateInput };
