/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FarmWhereUniqueInput } from "../../farm/base/FarmWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsDate,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { PlantWhereUniqueInput } from "../../plant/base/PlantWhereUniqueInput";
@InputType()
class CropCreateInput {
  @ApiProperty({
    required: false,
    type: () => FarmWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FarmWhereUniqueInput)
  @IsOptional()
  @Field(() => FarmWhereUniqueInput, {
    nullable: true,
  })
  farm?: FarmWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPlowed?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  nextGrowth?: Date | null;

  @ApiProperty({
    required: false,
    type: () => PlantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlantWhereUniqueInput)
  @IsOptional()
  @Field(() => PlantWhereUniqueInput, {
    nullable: true,
  })
  plant?: PlantWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stage?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  wateredAt?: Date | null;
}
export { CropCreateInput };
