/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCropArgs } from "./CreateCropArgs";
import { UpdateCropArgs } from "./UpdateCropArgs";
import { DeleteCropArgs } from "./DeleteCropArgs";
import { CropFindManyArgs } from "./CropFindManyArgs";
import { CropFindUniqueArgs } from "./CropFindUniqueArgs";
import { Crop } from "./Crop";
import { Farm } from "../../farm/base/Farm";
import { Plant } from "../../plant/base/Plant";
import { CropService } from "../crop.service";

@graphql.Resolver(() => Crop)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CropResolverBase {
  constructor(
    protected readonly service: CropService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "read",
    possession: "any",
  })
  async _cropsMeta(
    @graphql.Args() args: CropFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Crop])
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "read",
    possession: "any",
  })
  async crops(
    @graphql.Args() args: CropFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Crop[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Crop",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Crop, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "read",
    possession: "own",
  })
  async crop(
    @graphql.Args() args: CropFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Crop | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Crop",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Crop)
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "create",
    possession: "any",
  })
  async createCrop(
    @graphql.Args() args: CreateCropArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Crop> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Crop",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Crop"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        farm: args.data.farm
          ? {
              connect: args.data.farm,
            }
          : undefined,

        plant: args.data.plant
          ? {
              connect: args.data.plant,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Crop)
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "update",
    possession: "any",
  })
  async updateCrop(
    @graphql.Args() args: UpdateCropArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Crop | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Crop",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Crop"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          farm: args.data.farm
            ? {
                connect: args.data.farm,
              }
            : undefined,

          plant: args.data.plant
            ? {
                connect: args.data.plant,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Crop)
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "delete",
    possession: "any",
  })
  async deleteCrop(@graphql.Args() args: DeleteCropArgs): Promise<Crop | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Farm, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "read",
    possession: "any",
  })
  async farm(
    @graphql.Parent() parent: Crop,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Farm | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Farm",
    });
    const result = await this.service.getFarm(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Plant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Crop",
    action: "read",
    possession: "any",
  })
  async plant(
    @graphql.Parent() parent: Crop,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Plant | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Plant",
    });
    const result = await this.service.getPlant(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
